### ISSUE TITLE
Initial npm release 

### ISSUE THREAD

**Issue by chrmod** [ember-cli/watch-detector#3]
- [ ] move package under `ember-cli` or `broccoli` organization
- [x] enable `travisci` and `appveyor`
- [x] add README

**Comment by stefanpenner** [comment]
if you add me as an owner, i can quickly move it. (i dont' think i'm an owner, as i can't see the settings tab)

**Comment by chrmod** [comment]
@stefanpenner could not make you an owner of repository (from collaborators list), so I've transfer ownership to it directly to you.

**Comment by stefanpenner** [comment]
@chrmod i believe i have invited you to the ember-cli org. You should have sufficient power now.

**Comment by chrmod** [comment]
Looks like we've forgot the final step and never moved this repo. My permissions for ember-cli org are still not sufficient. 

I'm closing this issue and going to track the org transfer in https://github.com/chrmod/watch-detector/issues/9
