### ISSUE TITLE
Move into ember-cli org?

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/watch-detector#9]
This seems to be primarily created for ember-cli to use, and was an extraction of the detection logic from there I'd like to suggest moving the repo into the ember-cli org and adding a few more ember-cli contributors as npm owners. 

@chrmod - What do you think?

**Comment by chrmod** [comment]
@rwjblue that's a very good idea as I've completely forgot that this package even exists. 

I've tried to move it but don't have permissions to create repositories under ember-cli org.
Now you are also an admin of this repository so you should be able to transfer it.

Who would you like to be added to npm owners list?

**Comment by rwjblue** [comment]
Hehe, maybe you can initiate a transfer to me and then I’ll transfer into ember-cli?

**Comment by chrmod** [comment]
@rwjblue `rwjblue/watch-detector already exists` - you have to remove your fork first

**Comment by rwjblue** [comment]
Oh! I didn’t realize that, done!

**Comment by chrmod** [comment]
request sent

**Comment by rwjblue** [comment]
Thank you!
